### ISSUE TITLE
Concurrency issues with Kryo 5 

### ISSUE THREAD

**Issue by nvollmar** [altoo-ag/akka-kryo-serialization#237]
See https://github.com/EsotericSoftware/kryo/issues/798

```
Unable to find class: est-2
Serialization trace:
value (scala.Some)
value (io.altoo.akka.serialization.kryo.Sample1)
com.esotericsoftware.kryo.KryoException: Unable to find class: est-2
Serialization trace:
value (scala.Some)
value (io.altoo.akka.serialization.kryo.Sample1)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:190)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:691)
	at com.esotericsoftware.kryo.serializers.ReflectField.read(ReflectField.java:118)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:124)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:729)
	at com.esotericsoftware.kryo.serializers.ReflectField.read(ReflectField.java:125)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:124)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:810)
	at io.altoo.akka.serialization.kryo.ParallelSerializerTest.serializeDeserialize(ParallelSerializerTest.scala:43)
	at io.altoo.akka.serialization.kryo.ParallelSerializerTest.$anonfun$new$3(ParallelSerializerTest.scala:54)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:671)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at scala.concurrent.BatchingExecutor$AbstractBatch.runN(BatchingExecutor.scala:134)
	at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:163)
	at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:146)
	at scala.concurrent.BlockContext$.usingBlockContext(BlockContext.scala:107)
	at scala.concurrent.BatchingExecutor$AsyncBatch.run(BatchingExecutor.scala:154)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1425)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.ClassNotFoundException: est-2
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:416)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:184)
	... 24 more
```

Test reproducing those issues: 
* Akka based: https://github.com/altoo-ag/akka-kryo-serialization/blob/wip-parallel-serialization-issues-nvo/src/test/scala/io/altoo/akka/serialization/kryo/ParallelActorSystemSerializationTest.scala
* Plain Kryo: https://github.com/altoo-ag/akka-kryo-serialization/blob/wip-parallel-serialization-issues-nvo/src/test/scala/io/altoo/akka/serialization/kryo/ParallelSerializerTest.scala

**Comment by nvollmar** [comment]
Solved by disabling generic optimizations in 2.0.1
