### ISSUE TITLE
com.esotericsoftware.kryo.KryoException: Unable to find class: hone

### ISSUE THREAD

**Issue by behruz-b** [altoo-ag/akka-kryo-serialization#249]
While upgrading play2, akka to versions play2 - 2.7.7, akka - 2.6.12. Following exception happens:

```
com.esotericsoftware.kryo.KryoException: Unable to find class: hone
Serialization trace:
underlying (play.api.libs.json.JsObject)
value (scala.Some)
CASE_CLASS_FIELD1 (CASE_CLASS_FIELD1_PATH)
CASE_CLASS_FIELD2 (CASE_CLASS_FIELD2_PATH)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:190)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:691)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:802)
	at io.altoo.akka.serialization.kryo.serializer.scala.ScalaMutableMapSerializer.read(ScalaMapSerializers.scala:46)
	at io.altoo.akka.serialization.kryo.serializer.scala.ScalaMutableMapSerializer.read(ScalaMapSerializers.scala:38)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:729)
	at com.esotericsoftware.kryo.serializers.ReflectField.read(ReflectField.java:125)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:124)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:729)
Caused by: java.lang.ClassNotFoundException: hone
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:184)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:159)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:691)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:802)
	at io.altoo.akka.serialization.kryo.serializer.scala.ScalaMutableMapSerializer.read(ScalaMapSerializers.scala:46)
```
Please help to solve,
Thanks

**Comment by nvollmar** [comment]
Which version of akka-kryo-serialization are you using and can you provide a simplified test case to reproduce this problem?

**Comment by behruz-b** [comment]
"io.altoo" %% "akka-kryo-serialization" % "2.1.0"

**Comment by danischroeter** [comment]
stale issue - not enough info provided
