### ISSUE TITLE
throw exception  com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 504226268

### ISSUE THREAD

**Issue by wzy25** [altoo-ag/akka-kryo-serialization#68]
com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 504226268
    at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:137)
    at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:670)
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:781)
    at com.romix.akka.serialization.kryo.KryoBasedSerializer.fromBinary(KryoSerializer.scala:508)
    at com.romix.akka.serialization.kryo.KryoSerializer.fromBinary(KryoSerializer.scala:338)
    at akka.serialization.Serialization$$anonfun$deserialize$2.apply(Serialization.scala:124)
    at scala.util.Try$.apply(Try.scala:192)
    at akka.serialization.Serialization.deserialize(Serialization.scala:114)
    at akka.remote.serialization.MessageContainerSerializer.fromBinary(MessageContainerSerializer.scala:80)
    at akka.serialization.Serialization$$anonfun$deserialize$2.apply(Serialization.scala:124)
    at scala.util.Try$.apply(Try.scala:192)
    at akka.serialization.Serialization.deserialize(Serialization.scala:114)
    at akka.remote.MessageSerializer$.deserialize(MessageSerializer.scala:24)
    at akka.remote.DefaultMessageDispatcher.payload$lzycompute$1(Endpoint.scala:58)
    at akka.remote.DefaultMessageDispatcher.payload$1(Endpoint.scala:58)
    at akka.remote.DefaultMessageDispatcher.dispatch(Endpoint.scala:76)
    at akka.remote.EndpointReader$$anonfun$receive$2.applyOrElse(Endpoint.scala:953)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
    at akka.remote.EndpointActor.aroundReceive(Endpoint.scala:429)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
    at akka.actor.ActorCell.invoke(ActorCell.scala:495)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
    at akka.dispatch.Mailbox.run(Mailbox.scala:224)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

jar kryo-3.0.4-20151022.204923-5.jar
    akka-kryo-serialization_2.11-0.4.0.jar
minlog-1.3.0.jar

akka configuration:

  actor {
    provider = "akka.remote.RemoteActorRefProvider"
     serializers {
    java = "akka.serialization.JavaSerializer"
    //proto = "akka.remote.serialization.ProtobufSerializer"
    kryo = "com.romix.akka.serialization.kryo.KryoSerializer" 
                }
    serialization-bindings {
    "Message.AbstractMessage" = kryo
                }

  }

kyro configuration  in AKKA
kryo  {
      type = "graph"
    idstrategy = "default"
    serializer-pool-size = 16
    buffer-size = 4096
    max-buffer-size = -1

```
use-manifests = false

post-serialization-transformations = "lz4,aes"
implicit-registration-logging = all

kryo-trace = true

# Define mappings from a fully qualified class name to a numeric id.
# Smaller ids lead to smaller sizes of serialized representations.
#
# This section is mandatory for idstartegy=explicit
# This section is optional  for idstartegy=incremental
# This section is ignored   for idstartegy=default
#
# The smallest possible id should start at 20 (or even higher), because
# ids below it are used by Kryo internally e.g. for built-in Java and
# Scala types
mappings {
     "Message.MessageRemote" = 20
}

# Define a set of fully qualified class names for
# classes to be used for serialization.
# The ids for those classes will be assigned automatically,
# but respecting the order of declaration in this section
#
# This section is optional  for idstartegy=incremental
# This section is ignored   for idstartegy=default
# This section is optional  for idstartegy=explicit
classes = [

]
```

}

**Comment by wzy25** [comment]
AKKA version 2.4 
Scala version 2.11
And if use protobuf object,it works .

**Comment by briantopping** [comment]
You posted the stack trace but not the output of the serialization trace. If you didn't see it, probably because you don't have DEBUG level logging set. 

There are two options. One is to use `idstrategy=default` and `use-manifests=true`. The other is to look at the serialization trace of the sender and search the output for the class ID in question. The class name will be noted next to it in the initial registration. Add that class name to the mappings. 

If you want to short-circuit this iterative process of adding mappings, use `implicit-registration-logging = true`.

**Comment by jakub-vanek** [comment]
I'm getting the same exception (akka 2.4.16, scala 2.11.8).

For both `idstrategy = "default"` and `idstrategy = "automatic"`. If I set `use-manifests = true`, I get IndexOutOfBounds exceptions instead.

However, this **only** happens if I turn AES transformation on, otherwise everything works just fine.

Couldn't find the class ID in the sender trace as suggested. Only see `Register class name: xyz`.

**Comment by nvollmar** [comment]
Is this still an open problem or can we close this issue?
