### ISSUE TITLE
Akka cluster InvalidMessage Exception on stress test using compression (deflate )

### ISSUE THREAD

**Issue by kalamara** [altoo-ag/akka-kryo-serialization#99]
Hello, 
we are using AKKA 2.4.8 with scala 2.11.8  and akka-kryo-serialization 0.4.1.

We have set up an akka cluster (akka.cluster.ClusterActorRefProvider) with two nodes, one with 
akka-http (frontend) and one with 2 actor systems exchanging messages (backend). 
all messages are serialized with akka-kryo-serialization, and contain simple types and scala Lists.
When stress testing the system works perfectly with one frontend and one backend node, but when we add one more backend node to the cluster we get the exception

akka.actor.InvalidMessageException: Message is null
    at akka.pattern.PromiseActorRef.$bang(AskSupport.scala:533)
    at akka.remote.DefaultMessageDispatcher.dispatch(Endpoint.scala:92)
    at akka.remote.EndpointReader$$anonfun$receive$2.applyOrElse(Endpoint.scala:978)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
    at akka.remote.EndpointActor.aroundReceive(Endpoint.scala:447)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
    at akka.actor.ActorCell.invoke(ActorCell.scala:495)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
    at akka.dispatch.Mailbox.run(Mailbox.scala:224)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

this exception only appears under load and only when using deflate.

the  akka-kryo-serialization configuration is as follows:
kryo  {
        type = "nograph"
        idstrategy = "explicit"
        serializer-pool-size = 20000
        buffer-size = 98304
        max-buffer-size = 1048576
        use-manifests = false
        use-unsafe = false
        post-serialization-transformations = "deflate"
        implicit-registration-logging = true
        kryo-trace = false
        resolve-subclasses = false
        mappings {
          "scala.collection.immutable.$colon$colon" = 20, ...

**Comment by danischroeter** [comment]
fixed by #159 - thread safety issues of deflate
